//
//  ListManufacturerViewController.swift
//  Cartalogue
//
//  Created by Caio de Souza on 24/04/2018.
//  Copyright (c) 2018 Caio de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListManufacturerDisplayLogic: class{
  func displayFetchManufacturers(viewModel: ListManufacturers.FetchManufacturers.ViewModel)
  func updateCurrentPageLabel(viewModel: ListManufacturers.FetchManufacturers.ViewModel)
  func colorFor(_ indexPath: IndexPath) -> UIColor
  func presentAlert(title: String?, message: String?)
  func endRefreshControlIfNeeded()
  func selectManufacturer()
}

class ListManufacturerViewController: UIViewController, ListManufacturerDisplayLogic{
 
  var interactor: ListManufacturerBusinessLogic?
  var router: (NSObjectProtocol & ListManufacturerRoutingLogic & ListManufacturerDataPassing)?

  let pageSize: Int = 15
  var currentPage: Int = 0
  var displayedManufacturer: [ListManufacturers.FetchManufacturers.ViewModel.DisplayedManufacturer] = []
    
  // Outlets
  @IBOutlet weak var tableView: UITableView!
  @IBOutlet weak var registerCountLabel: UILabel!

  var refreshControl : UIRefreshControl = UIRefreshControl()
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?){
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
    
  }
  
  required init?(coder aDecoder: NSCoder){
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup(){
    let viewController = self
    let interactor = ListManufacturerInteractor()
    let presenter = ListManufacturerPresenter()
    let router = ListManufacturerRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
    
    private func setupTableView(){
      tableView.register(ManufacturerTableViewCell.self)
      tableView.refreshControl = refreshControl
      tableView.refreshControl?.addTarget(self, action: #selector(refreshControlTriggered(sender:)), for: .valueChanged)
        
    }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?){
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad(){
    super.viewDidLoad()
    setupTableView()
    doFetchManufacturers()
  }
    
  // MARK: ColorForIndexPath
  func colorFor(_ indexPath: IndexPath) -> UIColor{
    return indexPath.row % 2 == 0 ? UIColor(white: 0.0, alpha: 0.2) : UIColor(white: 1.0, alpha: 1.0)
  }
    
  
  // MARK: Do FetchManufacturers

  //Just a Wrapper to Use this as Target without modifyng the entire protocol
  @objc func objCDoFetchManufacturers(){
    currentPage += 1
    doFetchManufacturers()
  }
  
  func doFetchManufacturers(){
    registerCountLabel.text = "Fetching Next Page..."
    let request = ListManufacturers.FetchManufacturers.Request(parameters: ListManufacturers.ListManufacturerParameters(page: self.currentPage, pageSize: self.pageSize))
    interactor?.doFetchManufacturers(request: request)
  }
  
  func displayFetchManufacturers(viewModel: ListManufacturers.FetchManufacturers.ViewModel){
    displayedManufacturer.append(contentsOf: viewModel.displayedManufacturers)
    self.tableView.reloadData()
  }
    
  //MARK: Update Current Page Label
  func updateCurrentPageLabel(viewModel: ListManufacturers.FetchManufacturers.ViewModel) {
    registerCountLabel.text = "Fetched \(currentPage+1) pages of \(viewModel.totalPageCount)"
  }
    
  // MARK: Present Alert
  func presentAlert(title: String?, message: String?) {
   let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
    alertController.addAction(UIAlertAction(title: "Ok", style: .cancel, handler: { (alertAction) in
        alertController.dismiss(animated: true, completion: nil)
    }))
    self.present(alertController, animated: true, completion: nil)
  }
    
  // MARK: Refresh Control
    
  // He is mad now
  @objc func refreshControlTriggered(sender: UIRefreshControl){
    self.currentPage = 0
    self.displayedManufacturer.removeAll()
    doFetchManufacturers()
  }
  
  func endRefreshControlIfNeeded() {
    if refreshControl.isRefreshing{
      refreshControl.endRefreshing()
    }
  }
    
  // MARK: Select Manufacturer
  func selectManufacturer() {
    router?.routeToMainTypes(segue: nil)
  }
}

// MARK: UITableViewDelegate
extension ListManufacturerViewController : UITableViewDelegate{
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        if scrollView.isNearBottomEdge{
            if let _interactor = interactor, !_interactor.isLastPage(page: currentPage + 1){
                
                // Throttle
                NSObject.cancelPreviousPerformRequests(withTarget: self, selector: #selector(objCDoFetchManufacturers), object: nil)
                self.perform(#selector(objCDoFetchManufacturers), with: nil, afterDelay: 0.5)
            }
        }
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let selectedManufacturer = displayedManufacturer[indexPath.row]
        interactor?.selectManufacturer(request: ListManufacturers.SelectManufacturer.Selected(wkda: Wkda(id: selectedManufacturer.id, name: selectedManufacturer.name)))
    }
    
    
    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return "Page \(section+1)"
    }
    
    func tableView(_ tableView: UITableView, viewForFooterInSection section: Int) -> UIView? {
        return UIView()
    }
}


// MARK: UITableViewDataSource
extension ListManufacturerViewController : UITableViewDataSource{
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return self.currentPage+1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return min(self.pageSize, displayedManufacturer.count)
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let currentManufacturer = displayedManufacturer[indexPath.row]
        let cell = tableView.dequeueReusableCell(forIndexPath: indexPath) as ManufacturerTableViewCell
        cell.backgroundColor = colorFor(indexPath)
        cell.titleLabel.text = currentManufacturer.name
        cell.subtitleLabel.text = currentManufacturer.id
        return cell
    }
}
