//
//  MainTypesModels.swift
//  Cartalogue
//
//  Created by Caio de Souza on 27/04/2018.
//  Copyright (c) 2018 Caio de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


enum MainTypes {
    struct MainTypesParameters{
        var page: Int
        var pageSize: Int
        var manufacturerID: String
    }
  // MARK: Use cases
  
  enum FetchMainTypes {
    struct Request {
      var parameters: MainTypesParameters
    }
    struct Response {
        var mainTypes : APIManufacturer
    }
    struct ViewModel {
        var totalPageCount: Int
        struct DisplayedMainType{
            var name: String
        }
        var displayedMainType : [DisplayedMainType]
    }
  }
}
