//
//  ListManufacturerPresenterTests.swift
//  Cartalogue
//
//  Created by Caio de Souza on 28/04/2018.
//  Copyright (c) 2018 Caio de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Cartalogue
import XCTest

class ListManufacturerPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListManufacturerPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListManufacturerPresenter()
  }
  
  override func tearDown(){
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListManufacturerPresenter(){
    sut = ListManufacturerPresenter()
  }
  
  // MARK: Test doubles
  
    class ListManufacturerDisplayLogicSpy: ListManufacturerDisplayLogic{
        
    var colorForIndexPathCalled = false
    var presentAlertCalled = false
    var updateCurrentPageLabel = false
    var displayFetchManufacturersCalled = false
    var updateCurrentPageLabelCalled = false
    var endRefreshControlIfNeededCalled = false
    var selectManufacturerCalled = false
    var fetchManufacturersViewModel : ListManufacturers.FetchManufacturers.ViewModel!
    
    
    func displayFetchManufacturers(viewModel: ListManufacturers.FetchManufacturers.ViewModel) {
        displayFetchManufacturersCalled = true
        fetchManufacturersViewModel = viewModel
    }
    
    func updateCurrentPageLabel(viewModel: ListManufacturers.FetchManufacturers.ViewModel) {
        fetchManufacturersViewModel.displayedManufacturers.append(contentsOf: viewModel.displayedManufacturers)
        updateCurrentPageLabelCalled = true
    }
    
    func colorFor(_ indexPath: IndexPath) -> UIColor {
        colorForIndexPathCalled = true
        return UIColor.black
    }
    
    func presentAlert(title: String?, message: String?) {
        presentAlertCalled = true
    }
    
    func endRefreshControlIfNeeded() {
        endRefreshControlIfNeededCalled = true
    }
    
    func selectManufacturer() {
        selectManufacturerCalled = true
    }
    
  }
  
  // MARK: Tests
  
  func testPresentManufacturerShouldAskViewControllerToDisplayOrder()
  {
    // Given
    let spy = ListManufacturerDisplayLogicSpy()
    sut.viewController = spy
    let manufacturer = Seeds.API.page0APIManufacturer
    let response = ListManufacturers.FetchManufacturers.Response(manufacturer: manufacturer)
    
    // When
    sut.presentFetchManufacturers(response: response)
    
    // Then
    XCTAssertTrue(spy.displayFetchManufacturersCalled, "PresentManufacturer(response:) should ask the view controller to display the result")
  }
}
